### PR TITLE
fix(project-root): Get project-root depends on the fbounp

### PR DESCRIPTION
**Pull request by jcs090218**
For #4.

### CODE REVIEW

**Comment by jcs090218** [comment]
@bitti I have made some changes from the previous commit, it seems like having `(require 'project)` and check with `fboundp` would be a bit easier.

Let me know if you any objections on this! I would love to further discuss this issue. And of course, open Issue and PR are always welcome! 👍

**Comment by bitti** [comment]
That surely works too, but doesn't `(require 'project)` kind of defeat the purpose of autoloading? But the most important thing is that the functionality works.

**Comment by jcs090218** [comment]
Is the function `project-root` autoload? I think it should be good since this package itself would be wrapped too. 👍

**Comment by bitti** [comment]
> Is the function `project-root` autoload? I think it should be good since this package itself would be wrapped too. 👍

Not `project-root` but `project-current` and you had that in before without the explicit `require`. I suppose you still don't need it if you call `project-current` before the `fboundp` (e.g. via a `let` binding).

**Comment by jcs090218** [comment]
Ah... yes. You mentioned in the previous PR. May bad! Thanks for the information! ❤️

**Pull request merged**
